
APPLICATION = button

RIOTBASE ?= $(CURDIR)/../RIOT

BOARD ?= stm32f0discovery

DEVELHELP = 1

USEMODULE += xtimer

FEATURES_REQUIRED += periph_timer

FEATURES_REQUIRED += periph_gpio

FEATURES_REQUIRED += periph_gpio_irq

include $(RIOTBASE)/Makefile.include
